create table productos (
	id INT,
	producto VARCHAR(50),
	precio INT
);
insert into productos (id, producto, precio) values (1, 'Canadian Emmenthal', 87);
insert into productos (id, producto, precio) values (2, 'Beef - Ground, Extra Lean, Fresh', 1);
insert into productos (id, producto, precio) values (3, 'Pasta - Fettuccine, Dry', 70);
insert into productos (id, producto, precio) values (4, 'Pears - Fiorelle', 16);
insert into productos (id, producto, precio) values (5, 'Tea - Lemon Green Tea', 70);
insert into productos (id, producto, precio) values (6, 'Pasta - Cannelloni, Sheets, Fresh', 45);
insert into productos (id, producto, precio) values (7, 'Shallots', 1);
insert into productos (id, producto, precio) values (8, 'Carbonated Water - Peach', 75);
insert into productos (id, producto, precio) values (9, 'Pork - Bacon, Double Smoked', 23);
insert into productos (id, producto, precio) values (10, 'Yams', 23);
insert into productos (id, producto, precio) values (11, 'Cookie Dough - Double', 61);
insert into productos (id, producto, precio) values (12, 'Daikon Radish', 81);
insert into productos (id, producto, precio) values (13, 'Rum - Dark, Bacardi, Black', 40);
insert into productos (id, producto, precio) values (14, 'Corn - On The Cob', 57);
insert into productos (id, producto, precio) values (15, 'Crab - Claws, 26 - 30', 53);
insert into productos (id, producto, precio) values (16, 'Pasta - Linguini, Dry', 77);
insert into productos (id, producto, precio) values (17, 'Cabbage - Red', 94);
insert into productos (id, producto, precio) values (18, 'Cake - Sheet Strawberry', 63);
insert into productos (id, producto, precio) values (19, 'Container - Hngd Cll Blk 7x7x3', 26);
insert into productos (id, producto, precio) values (20, 'Onions - Dried, Chopped', 42);
insert into productos (id, producto, precio) values (21, 'Sprouts - Alfalfa', 8);
insert into productos (id, producto, precio) values (22, 'Oregano - Dry, Rubbed', 76);
insert into productos (id, producto, precio) values (23, 'Muffin Mix - Chocolate Chip', 22);
insert into productos (id, producto, precio) values (24, 'Cookie - Oreo 100x2', 71);
insert into productos (id, producto, precio) values (25, 'Knife Plastic - White', 65);
insert into productos (id, producto, precio) values (26, 'Pepper - Paprika, Spanish', 27);
insert into productos (id, producto, precio) values (27, 'Calypso - Pineapple Passion', 23);
insert into productos (id, producto, precio) values (28, 'Oil - Cooking Spray', 99);
insert into productos (id, producto, precio) values (29, 'Lambcasing', 97);
insert into productos (id, producto, precio) values (30, 'Sauce - Marinara', 80);
insert into productos (id, producto, precio) values (31, 'Wanton Wrap', 27);
insert into productos (id, producto, precio) values (32, 'Cheese - Gouda', 63);
insert into productos (id, producto, precio) values (33, 'Mustard - Dijon', 9);
insert into productos (id, producto, precio) values (34, 'Napkin White', 13);
insert into productos (id, producto, precio) values (35, 'Mangoes', 81);
insert into productos (id, producto, precio) values (36, 'Wine - Carmenere Casillero Del', 54);
insert into productos (id, producto, precio) values (37, 'Quinoa', 86);
insert into productos (id, producto, precio) values (38, 'Wine - White, Pinot Grigio', 76);
insert into productos (id, producto, precio) values (39, 'Wine - Magnotta - Cab Sauv', 90);
insert into productos (id, producto, precio) values (40, 'Oil - Pumpkinseed', 45);
insert into productos (id, producto, precio) values (41, 'Wine - Remy Pannier Rose', 51);
insert into productos (id, producto, precio) values (42, 'Basil - Pesto Sauce', 70);
insert into productos (id, producto, precio) values (43, 'Bananas', 83);
insert into productos (id, producto, precio) values (44, 'Milk - 1%', 27);
insert into productos (id, producto, precio) values (45, 'Brownies - Two Bite, Chocolate', 31);
insert into productos (id, producto, precio) values (46, 'Lettuce - California Mix', 53);
insert into productos (id, producto, precio) values (47, 'Pork Casing', 76);
insert into productos (id, producto, precio) values (48, 'Yoplait - Strawbrasp Peac', 73);
insert into productos (id, producto, precio) values (49, 'Potatoes - Peeled', 79);
insert into productos (id, producto, precio) values (50, 'Pasta - Penne, Lisce, Dry', 18);
insert into productos (id, producto, precio) values (51, 'Chef Hat 25cm', 71);
insert into productos (id, producto, precio) values (52, 'Salmon - Atlantic, No Skin', 44);
insert into productos (id, producto, precio) values (53, 'Corn Shoots', 72);
insert into productos (id, producto, precio) values (54, 'Wine - Zonnebloem Pinotage', 44);
insert into productos (id, producto, precio) values (55, 'Pork - Sausage, Medium', 86);
insert into productos (id, producto, precio) values (56, 'Oil - Avocado', 56);
insert into productos (id, producto, precio) values (57, 'Food Colouring - Blue', 41);
insert into productos (id, producto, precio) values (58, 'Coconut - Whole', 64);
insert into productos (id, producto, precio) values (59, 'Cheese - Goat With Herbs', 31);
insert into productos (id, producto, precio) values (60, 'Sugar - Monocystal / Rock', 81);
insert into productos (id, producto, precio) values (61, 'Nut - Pistachio, Shelled', 9);
insert into productos (id, producto, precio) values (62, 'Wine - Casillero Del Diablo', 30);
insert into productos (id, producto, precio) values (63, 'Wine - Harrow Estates, Vidal', 55);
insert into productos (id, producto, precio) values (64, 'Coffee Cup 12oz 5342cd', 94);
insert into productos (id, producto, precio) values (65, 'Basil - Primerba, Paste', 91);
insert into productos (id, producto, precio) values (66, 'Nut - Chestnuts, Whole', 68);
insert into productos (id, producto, precio) values (67, 'Yoplait - Strawbrasp Peac', 85);
insert into productos (id, producto, precio) values (68, 'Apple - Macintosh', 23);
insert into productos (id, producto, precio) values (69, 'Roe - White Fish', 20);
insert into productos (id, producto, precio) values (70, 'Longos - Chicken Cordon Bleu', 50);
insert into productos (id, producto, precio) values (71, 'Beef - Tenderloin', 5);
insert into productos (id, producto, precio) values (72, 'Cheese Cloth No 100', 54);
insert into productos (id, producto, precio) values (73, 'Cheese - Brie, Triple Creme', 57);
insert into productos (id, producto, precio) values (74, 'Wine - Alsace Riesling Reserve', 9);
insert into productos (id, producto, precio) values (75, 'Cheese - Bocconcini', 88);
insert into productos (id, producto, precio) values (76, 'Sauce - Bernaise, Mix', 20);
insert into productos (id, producto, precio) values (77, 'Cheese - Grana Padano', 60);
insert into productos (id, producto, precio) values (78, 'Sauce - Cranberry', 33);
insert into productos (id, producto, precio) values (79, 'Orange Roughy 4/6 Oz', 44);
insert into productos (id, producto, precio) values (80, 'Cinnamon Buns Sticky', 97);
insert into productos (id, producto, precio) values (81, 'Cheese - Mozzarella, Buffalo', 74);
insert into productos (id, producto, precio) values (82, 'Cookie Dough - Chunky', 3);
insert into productos (id, producto, precio) values (83, 'Apples - Spartan', 81);
insert into productos (id, producto, precio) values (84, 'Coffee - Ristretto Coffee Capsule', 59);
insert into productos (id, producto, precio) values (85, 'Wine - Prosecco Valdobienne', 64);
insert into productos (id, producto, precio) values (86, 'Gatorade - Lemon Lime', 26);
insert into productos (id, producto, precio) values (87, 'Pepper - Red Thai', 76);
insert into productos (id, producto, precio) values (88, 'Pie Box - Cello Window 2.5', 35);
insert into productos (id, producto, precio) values (89, 'Wine - Vineland Estate Semi - Dry', 76);
insert into productos (id, producto, precio) values (90, 'Chocolate Bar - Oh Henry', 34);
insert into productos (id, producto, precio) values (91, 'Salmon Atl.whole 8 - 10 Lb', 18);
insert into productos (id, producto, precio) values (92, 'Chef Hat 20cm', 19);
insert into productos (id, producto, precio) values (93, 'Sauce - Demi Glace', 99);
insert into productos (id, producto, precio) values (94, 'Longos - Penne With Pesto', 8);
insert into productos (id, producto, precio) values (95, 'Bread - Raisin', 27);
insert into productos (id, producto, precio) values (96, 'Red Snapper - Fillet, Skin On', 73);
insert into productos (id, producto, precio) values (97, 'Scotch - Queen Anne', 99);
insert into productos (id, producto, precio) values (98, 'Veal - Leg', 54);
insert into productos (id, producto, precio) values (99, 'Bread - Bistro Sour', 53);
insert into productos (id, producto, precio) values (100, 'Napkin Colour', 92);
insert into productos (id, producto, precio) values (101, 'Roe - White Fish', 47);
insert into productos (id, producto, precio) values (102, 'Orange - Tangerine', 5);
insert into productos (id, producto, precio) values (103, 'Tea - Honey Green Tea', 71);
insert into productos (id, producto, precio) values (104, 'Veal - Nuckle', 24);
insert into productos (id, producto, precio) values (105, 'Turkey - Breast, Smoked', 40);
insert into productos (id, producto, precio) values (106, 'Bread - Olive Dinner Roll', 41);
insert into productos (id, producto, precio) values (107, 'Wine - Chianti Classico Riserva', 41);
insert into productos (id, producto, precio) values (108, 'Beef - Bones, Cut - Up', 57);
insert into productos (id, producto, precio) values (109, 'Wine - Magnotta - Red, Baco', 63);
insert into productos (id, producto, precio) values (110, 'Basil - Fresh', 56);
insert into productos (id, producto, precio) values (111, 'Strawberries - California', 85);
insert into productos (id, producto, precio) values (112, 'Water - Aquafina Vitamin', 99);
insert into productos (id, producto, precio) values (113, 'Tart Shells - Sweet, 3', 60);
insert into productos (id, producto, precio) values (114, 'Lid Tray - 16in Dome', 17);
insert into productos (id, producto, precio) values (115, 'Wine - Vovray Sec Domaine Huet', 71);
insert into productos (id, producto, precio) values (116, 'Chocolate - Dark Callets', 67);
insert into productos (id, producto, precio) values (117, 'Wine - Rhine Riesling Wolf Blass', 47);
insert into productos (id, producto, precio) values (118, 'Cumin - Whole', 85);
insert into productos (id, producto, precio) values (119, 'Juice - Apple Cider', 19);
insert into productos (id, producto, precio) values (120, 'Wine - Ruffino Chianti', 27);
insert into productos (id, producto, precio) values (121, 'Salt - Sea', 69);
insert into productos (id, producto, precio) values (122, 'Yoplait - Strawbrasp Peac', 3);
insert into productos (id, producto, precio) values (123, 'Shopper Bag - S - 4', 17);
insert into productos (id, producto, precio) values (124, 'Mushroom - Trumpet, Dry', 54);
insert into productos (id, producto, precio) values (125, 'Coffee Caramel Biscotti', 46);
insert into productos (id, producto, precio) values (126, 'Sauce - Bernaise, Mix', 90);
insert into productos (id, producto, precio) values (127, 'Ham - Cooked Italian', 82);
insert into productos (id, producto, precio) values (128, 'Beef - Top Butt Aaa', 74);
insert into productos (id, producto, precio) values (129, 'Stock - Fish', 78);
insert into productos (id, producto, precio) values (130, 'Gingerale - Schweppes, 355 Ml', 97);
insert into productos (id, producto, precio) values (131, 'Neckerchief Blck', 36);
insert into productos (id, producto, precio) values (132, 'Bread Country Roll', 9);
insert into productos (id, producto, precio) values (133, 'Dill - Primerba, Paste', 97);
insert into productos (id, producto, precio) values (134, 'Egg - Salad Premix', 27);
insert into productos (id, producto, precio) values (135, 'Lotus Root', 18);
insert into productos (id, producto, precio) values (136, 'Compound - Rum', 87);
insert into productos (id, producto, precio) values (137, 'Wine - White, Cooking', 11);
insert into productos (id, producto, precio) values (138, 'Bread - Roll, Whole Wheat', 12);
insert into productos (id, producto, precio) values (139, 'Cake - French Pear Tart', 91);
insert into productos (id, producto, precio) values (140, 'Oats Large Flake', 98);
insert into productos (id, producto, precio) values (141, 'Sauce - Cranberry', 66);
insert into productos (id, producto, precio) values (142, 'Bar Energy Chocchip', 84);
insert into productos (id, producto, precio) values (143, 'Tortillas - Flour, 10', 18);
insert into productos (id, producto, precio) values (144, 'Bacon Strip Precooked', 86);
insert into productos (id, producto, precio) values (145, 'Ham - Cooked Italian', 78);
insert into productos (id, producto, precio) values (146, 'Fish - Atlantic Salmon, Cold', 59);
insert into productos (id, producto, precio) values (147, 'Wine - Jafflin Bourgongone', 64);
insert into productos (id, producto, precio) values (148, 'Wine - Red, Harrow Estates, Cab', 44);
insert into productos (id, producto, precio) values (149, 'Olive - Spread Tapenade', 72);
insert into productos (id, producto, precio) values (150, 'Quail Eggs - Canned', 44);
insert into productos (id, producto, precio) values (151, 'Wakami Seaweed', 44);
insert into productos (id, producto, precio) values (152, 'Sugar - Brown', 6);
insert into productos (id, producto, precio) values (153, 'Ice Cream - Vanilla', 64);
insert into productos (id, producto, precio) values (154, 'Ecolab - Solid Fusion', 47);
insert into productos (id, producto, precio) values (155, 'Salt - Kosher', 42);
insert into productos (id, producto, precio) values (156, 'Emulsifier', 3);
insert into productos (id, producto, precio) values (157, 'Cheese - Asiago', 92);
insert into productos (id, producto, precio) values (158, 'Mushroom - Chanterelle Frozen', 35);
insert into productos (id, producto, precio) values (159, 'Wasabi Paste', 42);
insert into productos (id, producto, precio) values (160, 'Pepper - Sorrano', 85);
insert into productos (id, producto, precio) values (161, 'Beer - Mill St Organic', 73);
insert into productos (id, producto, precio) values (162, 'Dr. Pepper - 355ml', 27);
insert into productos (id, producto, precio) values (163, 'Nantucket - Kiwi Berry Cktl.', 14);
insert into productos (id, producto, precio) values (164, 'Beans - Soya Bean', 18);
insert into productos (id, producto, precio) values (165, 'Numi - Assorted Teas', 79);
insert into productos (id, producto, precio) values (166, 'V8 - Tropical Blend', 41);
insert into productos (id, producto, precio) values (167, 'Kohlrabi', 87);
insert into productos (id, producto, precio) values (168, 'Cookies - Oreo, 4 Pack', 85);
insert into productos (id, producto, precio) values (169, 'Pastry - Baked Cinnamon Stick', 91);
insert into productos (id, producto, precio) values (170, 'Lamb Shoulder Boneless Nz', 98);
insert into productos (id, producto, precio) values (171, 'Coffee - Almond Amaretto', 52);
insert into productos (id, producto, precio) values (172, 'Cookies - Assorted', 46);
insert into productos (id, producto, precio) values (173, 'Sterno - Chafing Dish Fuel', 26);
insert into productos (id, producto, precio) values (174, 'Grouper - Fresh', 5);
insert into productos (id, producto, precio) values (175, 'Cheese - Comte', 28);
insert into productos (id, producto, precio) values (176, 'Cheese - Swiss', 87);
insert into productos (id, producto, precio) values (177, 'Sausage - Blood Pudding', 59);
insert into productos (id, producto, precio) values (178, 'Wine - Chenin Blanc K.w.v.', 20);
insert into productos (id, producto, precio) values (179, 'Sauce - Apple, Unsweetened', 79);
insert into productos (id, producto, precio) values (180, 'Berry Brulee', 60);
insert into productos (id, producto, precio) values (181, 'Lettuce - Belgian Endive', 42);
insert into productos (id, producto, precio) values (182, 'Kellogs Cereal In A Cup', 55);
insert into productos (id, producto, precio) values (183, 'Irish Cream - Butterscotch', 18);
insert into productos (id, producto, precio) values (184, 'The Pop Shoppe - Root Beer', 31);
insert into productos (id, producto, precio) values (185, 'Wine - Barolo Fontanafredda', 74);
insert into productos (id, producto, precio) values (186, 'Bandage - Fexible 1x3', 83);
insert into productos (id, producto, precio) values (187, 'Gooseberry', 74);
insert into productos (id, producto, precio) values (188, 'Soup Campbells Turkey Veg.', 18);
insert into productos (id, producto, precio) values (189, 'Nectarines', 45);
insert into productos (id, producto, precio) values (190, 'Scotch - Queen Anne', 3);
insert into productos (id, producto, precio) values (191, 'Aspic - Light', 36);
insert into productos (id, producto, precio) values (192, 'Cod - Salted, Boneless', 83);
insert into productos (id, producto, precio) values (193, 'Cheese - Comtomme', 49);
insert into productos (id, producto, precio) values (194, 'Mace Ground', 8);
insert into productos (id, producto, precio) values (195, 'Table Cloth 62x114 Colour', 75);
insert into productos (id, producto, precio) values (196, 'Oil - Macadamia', 97);
insert into productos (id, producto, precio) values (197, 'Lemon Grass', 68);
insert into productos (id, producto, precio) values (198, 'Sprouts - Pea', 81);
insert into productos (id, producto, precio) values (199, 'Ocean Spray - Kiwi Strawberry', 66);
insert into productos (id, producto, precio) values (200, 'Wine - Sauvignon Blanc', 27);
insert into productos (id, producto, precio) values (201, 'Puree - Kiwi', 81);
insert into productos (id, producto, precio) values (202, 'Chocolate - Milk Coating', 7);
insert into productos (id, producto, precio) values (203, 'Muffin Mix - Blueberry', 89);
insert into productos (id, producto, precio) values (204, 'Pastry - Baked Scones - Mini', 86);
insert into productos (id, producto, precio) values (205, 'Spinach - Baby', 64);
insert into productos (id, producto, precio) values (206, 'Pasta - Fettuccine, Egg, Fresh', 3);
insert into productos (id, producto, precio) values (207, 'Mushroom - Shitake, Dry', 75);
insert into productos (id, producto, precio) values (208, 'Cheese - Roquefort Pappillon', 57);
insert into productos (id, producto, precio) values (209, 'Muffin - Blueberry Individual', 66);
insert into productos (id, producto, precio) values (210, 'Flour - Cake', 57);
insert into productos (id, producto, precio) values (211, 'Coconut - Creamed, Pure', 73);
insert into productos (id, producto, precio) values (212, 'Coconut - Shredded, Sweet', 86);
insert into productos (id, producto, precio) values (213, 'Cheese - Provolone', 78);
insert into productos (id, producto, precio) values (214, 'Sugar - Invert', 67);
insert into productos (id, producto, precio) values (215, 'Water - Tonic', 78);
insert into productos (id, producto, precio) values (216, 'Juice - Grape, White', 40);
insert into productos (id, producto, precio) values (217, 'Sauce - Mint', 29);
insert into productos (id, producto, precio) values (218, 'Sambuca Cream', 24);
insert into productos (id, producto, precio) values (219, 'Cut Wakame - Hanawakaba', 26);
insert into productos (id, producto, precio) values (220, 'Tuna - Salad Premix', 45);
insert into productos (id, producto, precio) values (221, 'Coffee - Ristretto Coffee Capsule', 6);
insert into productos (id, producto, precio) values (222, 'Cake - Cake Sheet Macaroon', 96);
insert into productos (id, producto, precio) values (223, 'Chinese Lemon Pork', 87);
insert into productos (id, producto, precio) values (224, 'Flavouring - Orange', 49);
insert into productos (id, producto, precio) values (225, 'Sloe Gin - Mcguinness', 69);
insert into productos (id, producto, precio) values (226, 'Beer - Molson Excel', 71);
insert into productos (id, producto, precio) values (227, 'Wine - Fat Bastard Merlot', 59);
insert into productos (id, producto, precio) values (228, 'Shortbread - Cookie Crumbs', 79);
insert into productos (id, producto, precio) values (229, 'Kolrabi', 58);
insert into productos (id, producto, precio) values (230, 'Fish - Soup Base, Bouillon', 86);
insert into productos (id, producto, precio) values (231, 'Chocolate - Dark Callets', 32);
insert into productos (id, producto, precio) values (232, 'Ecolab - Ster Bac', 39);
insert into productos (id, producto, precio) values (233, 'Steam Pan Full Lid', 59);
insert into productos (id, producto, precio) values (234, 'Tea - Mint', 26);
insert into productos (id, producto, precio) values (235, 'Barley - Pearl', 57);
insert into productos (id, producto, precio) values (236, 'Pail With Metal Handle 16l White', 76);
insert into productos (id, producto, precio) values (237, 'Doilies - 5, Paper', 26);
insert into productos (id, producto, precio) values (238, 'Mushroom - Lg - Cello', 19);
insert into productos (id, producto, precio) values (239, 'Extract Vanilla Pure', 77);
insert into productos (id, producto, precio) values (240, 'Bread - Italian Corn Meal Poly', 59);
insert into productos (id, producto, precio) values (241, 'Pie Shell - 9', 64);
insert into productos (id, producto, precio) values (242, 'Vermouth - White, Cinzano', 61);
insert into productos (id, producto, precio) values (243, 'Tomatoes - Heirloom', 22);
insert into productos (id, producto, precio) values (244, 'Juice - Cranberry, 341 Ml', 44);
insert into productos (id, producto, precio) values (245, 'Longos - Lasagna Beef', 71);
insert into productos (id, producto, precio) values (246, 'Mcgillicuddy Vanilla Schnap', 75);
insert into productos (id, producto, precio) values (247, 'Basil - Seedlings Cookstown', 32);
insert into productos (id, producto, precio) values (248, 'Liners - Banana, Paper', 69);
insert into productos (id, producto, precio) values (249, 'Potatoes - Purple, Organic', 3);
insert into productos (id, producto, precio) values (250, 'Cake - Night And Day Choclate', 61);
insert into productos (id, producto, precio) values (251, 'Emulsifier', 34);
insert into productos (id, producto, precio) values (252, 'Venison - Liver', 1);
insert into productos (id, producto, precio) values (253, 'Red Cod Fillets - 225g', 5);
insert into productos (id, producto, precio) values (254, 'Wine - Magnotta, Merlot Sr Vqa', 41);
insert into productos (id, producto, precio) values (255, 'Clementine', 34);
insert into productos (id, producto, precio) values (256, 'Wine - White, French Cross', 51);
insert into productos (id, producto, precio) values (257, 'Chocolate Bar - Smarties', 28);
insert into productos (id, producto, precio) values (258, 'Beef - Tenderlion, Center Cut', 25);
insert into productos (id, producto, precio) values (259, 'Wine - White, Ej', 5);
insert into productos (id, producto, precio) values (260, 'Pork - Ground', 43);
insert into productos (id, producto, precio) values (261, 'Schnappes - Peach, Walkers', 20);
insert into productos (id, producto, precio) values (262, 'Cream - 18%', 64);
insert into productos (id, producto, precio) values (263, 'Glass Clear 7 Oz Xl', 81);
insert into productos (id, producto, precio) values (264, 'Cheese - Gorgonzola', 16);
insert into productos (id, producto, precio) values (265, 'Appetizer - Sausage Rolls', 26);
insert into productos (id, producto, precio) values (266, 'Soup - Campbells Chili Veg', 36);
insert into productos (id, producto, precio) values (267, 'Dried Cherries', 3);
insert into productos (id, producto, precio) values (268, 'Pail - 15l White, With Handle', 16);
insert into productos (id, producto, precio) values (269, 'Eggplant - Regular', 20);
insert into productos (id, producto, precio) values (270, 'Stock - Veal, White', 82);
insert into productos (id, producto, precio) values (271, 'Veal - Sweetbread', 84);
insert into productos (id, producto, precio) values (272, 'Cheese - Grie Des Champ', 98);
insert into productos (id, producto, precio) values (273, 'Glass Clear 7 Oz Xl', 65);
insert into productos (id, producto, precio) values (274, 'Pork - Smoked Kassler', 50);
insert into productos (id, producto, precio) values (275, 'Squeeze Bottle', 2);
insert into productos (id, producto, precio) values (276, 'Straw - Regular', 28);
insert into productos (id, producto, precio) values (277, 'Oil - Safflower', 11);
insert into productos (id, producto, precio) values (278, 'Maintenance Removal Charge', 37);
insert into productos (id, producto, precio) values (279, 'Tequila - Sauza Silver', 65);
insert into productos (id, producto, precio) values (280, 'Allspice - Jamaican', 94);
insert into productos (id, producto, precio) values (281, 'Syrup - Kahlua Chocolate', 70);
insert into productos (id, producto, precio) values (282, 'Beans - Green', 43);
insert into productos (id, producto, precio) values (283, 'Mangoes', 34);
insert into productos (id, producto, precio) values (284, 'Lamb - Ground', 21);
insert into productos (id, producto, precio) values (285, 'Asparagus - White, Canned', 59);
insert into productos (id, producto, precio) values (286, 'Nut - Almond, Blanched, Whole', 96);
insert into productos (id, producto, precio) values (287, 'The Pop Shoppe Pinapple', 18);
insert into productos (id, producto, precio) values (288, 'Beef - Short Loin', 89);
insert into productos (id, producto, precio) values (289, 'Wine - Stoneliegh Sauvignon', 63);
insert into productos (id, producto, precio) values (290, 'Smirnoff Green Apple Twist', 17);
insert into productos (id, producto, precio) values (291, 'Cheese - Mozzarella, Buffalo', 66);
insert into productos (id, producto, precio) values (292, 'Island Oasis - Banana Daiquiri', 2);
insert into productos (id, producto, precio) values (293, 'Wheat - Soft Kernal Of Wheat', 52);
insert into productos (id, producto, precio) values (294, 'Tortillas - Flour, 10', 71);
insert into productos (id, producto, precio) values (295, 'Vanilla Beans', 86);
insert into productos (id, producto, precio) values (296, 'Sauce Tomato Pouch', 84);
insert into productos (id, producto, precio) values (297, 'Munchies Honey Sweet Trail Mix', 45);
insert into productos (id, producto, precio) values (298, 'Food Colouring - Blue', 13);
insert into productos (id, producto, precio) values (299, 'Beef - Kobe Striploin', 73);
insert into productos (id, producto, precio) values (300, 'Campari', 97);
insert into productos (id, producto, precio) values (301, 'Sugar - Brown, Individual', 99);
insert into productos (id, producto, precio) values (302, 'Mix - Cocktail Strawberry Daiquiri', 52);
insert into productos (id, producto, precio) values (303, 'Ice Cream - Super Sandwich', 22);
insert into productos (id, producto, precio) values (304, 'Water - Aquafina Vitamin', 92);
insert into productos (id, producto, precio) values (305, 'Blouse / Shirt / Sweater', 38);
insert into productos (id, producto, precio) values (306, 'Wine - Cahors Ac 2000, Clos', 31);
insert into productos (id, producto, precio) values (307, 'Chicken - Wieners', 98);
insert into productos (id, producto, precio) values (308, 'Pear - Asian', 97);
insert into productos (id, producto, precio) values (309, 'Wine - Red, Black Opal Shiraz', 29);
insert into productos (id, producto, precio) values (310, 'Tea - Lemon Green Tea', 58);
insert into productos (id, producto, precio) values (311, 'Cheese - Manchego, Spanish', 24);
insert into productos (id, producto, precio) values (312, 'Flour - Whole Wheat', 99);
insert into productos (id, producto, precio) values (313, 'Jolt Cola - Red Eye', 64);
insert into productos (id, producto, precio) values (314, 'Cup Translucent 9 Oz', 3);
insert into productos (id, producto, precio) values (315, 'Oil - Shortening - All - Purpose', 97);
insert into productos (id, producto, precio) values (316, 'Juice - Apple 284ml', 42);
insert into productos (id, producto, precio) values (317, 'Beans - French', 63);
insert into productos (id, producto, precio) values (318, 'Island Oasis - Raspberry', 38);
insert into productos (id, producto, precio) values (319, 'Pasta - Agnolotti - Butternut', 69);
insert into productos (id, producto, precio) values (320, 'Ezy Change Mophandle', 16);
insert into productos (id, producto, precio) values (321, 'Wine - Saint Emilion Calvet', 29);
insert into productos (id, producto, precio) values (322, 'Wine - Magnotta - Belpaese', 21);
insert into productos (id, producto, precio) values (323, 'Flour Pastry Super Fine', 36);
insert into productos (id, producto, precio) values (324, 'Milk - Chocolate 250 Ml', 20);
insert into productos (id, producto, precio) values (325, 'Bagel - Plain', 14);
insert into productos (id, producto, precio) values (326, 'Brandy Apricot', 8);
insert into productos (id, producto, precio) values (327, 'Onion Powder', 91);
insert into productos (id, producto, precio) values (328, 'Tuna - Bluefin', 17);
insert into productos (id, producto, precio) values (329, 'Table Cloth 91x91 Colour', 92);
insert into productos (id, producto, precio) values (330, 'Beer - True North Strong Ale', 21);
insert into productos (id, producto, precio) values (331, 'Tamarillo', 67);
insert into productos (id, producto, precio) values (332, 'Steamers White', 94);
insert into productos (id, producto, precio) values (333, 'Icecream - Dstk Strw Chseck', 31);
insert into productos (id, producto, precio) values (334, 'Bread - Pain Au Liat X12', 83);
insert into productos (id, producto, precio) values (335, 'Tea - Lemon Scented', 73);
insert into productos (id, producto, precio) values (336, 'Rice - Sushi', 61);
insert into productos (id, producto, precio) values (337, 'Pear - Prickly', 55);
insert into productos (id, producto, precio) values (338, 'Flavouring - Raspberry', 43);
insert into productos (id, producto, precio) values (339, 'Capers - Ox Eye Daisy', 42);
insert into productos (id, producto, precio) values (340, 'Gatorade - Orange', 21);
insert into productos (id, producto, precio) values (341, 'Bag Stand', 91);
insert into productos (id, producto, precio) values (342, 'Beef - Cow Feet Split', 37);
insert into productos (id, producto, precio) values (343, 'Juice - V8 Splash', 91);
insert into productos (id, producto, precio) values (344, 'Flour - Chickpea', 98);
insert into productos (id, producto, precio) values (345, 'Soup Campbells - Italian Wedding', 16);
insert into productos (id, producto, precio) values (346, 'Bulgar', 10);
insert into productos (id, producto, precio) values (347, 'Raspberries - Fresh', 69);
insert into productos (id, producto, precio) values (348, 'Bread - Bagels, Plain', 10);
insert into productos (id, producto, precio) values (349, 'Bread - Raisin Walnut Pull', 36);
insert into productos (id, producto, precio) values (350, 'Pork - Chop, Frenched', 32);
insert into productos (id, producto, precio) values (351, 'Garam Marsala', 84);
insert into productos (id, producto, precio) values (352, 'Pepper - Red Thai', 2);
insert into productos (id, producto, precio) values (353, 'Cheese - Parmigiano Reggiano', 26);
insert into productos (id, producto, precio) values (354, 'Soap - Pine Sol Floor Cleaner', 15);
insert into productos (id, producto, precio) values (355, 'Bread - Focaccia Quarter', 64);
insert into productos (id, producto, precio) values (356, 'Taro Leaves', 71);
insert into productos (id, producto, precio) values (357, 'Bols Melon Liqueur', 92);
insert into productos (id, producto, precio) values (358, 'Tomato - Green', 63);
insert into productos (id, producto, precio) values (359, 'Creme De Menth - White', 3);
insert into productos (id, producto, precio) values (360, 'Bagel - Ched Chs Presliced', 7);
insert into productos (id, producto, precio) values (361, 'Kaffir Lime Leaves', 19);
insert into productos (id, producto, precio) values (362, 'Bread - Bagels, Plain', 82);
insert into productos (id, producto, precio) values (363, 'Chocolate - Feathers', 6);
insert into productos (id, producto, precio) values (364, 'Chicken - Whole Fryers', 20);
insert into productos (id, producto, precio) values (365, 'Energy Drink Bawls', 53);
insert into productos (id, producto, precio) values (366, 'Dates', 14);
insert into productos (id, producto, precio) values (367, 'Danishes - Mini Raspberry', 52);
insert into productos (id, producto, precio) values (368, 'Nut - Pistachio, Shelled', 92);
insert into productos (id, producto, precio) values (369, 'Coffee Cup 16oz Foam', 83);
insert into productos (id, producto, precio) values (370, 'Munchies Honey Sweet Trail Mix', 79);
insert into productos (id, producto, precio) values (371, 'Pastry - Apple Large', 87);
insert into productos (id, producto, precio) values (372, 'Tomatoes - Hot House', 46);
insert into productos (id, producto, precio) values (373, 'Mangoes', 39);
insert into productos (id, producto, precio) values (374, 'Strawberries', 3);
insert into productos (id, producto, precio) values (375, 'Lentils - Green, Dry', 91);
insert into productos (id, producto, precio) values (376, 'Turkey - Breast, Double', 61);
insert into productos (id, producto, precio) values (377, 'Banana', 45);
insert into productos (id, producto, precio) values (378, 'Bay Leaf Fresh', 8);
insert into productos (id, producto, precio) values (379, 'Olive - Spread Tapenade', 79);
insert into productos (id, producto, precio) values (380, 'Wine - White Cab Sauv.on', 39);
insert into productos (id, producto, precio) values (381, 'Bagel - Ched Chs Presliced', 43);
insert into productos (id, producto, precio) values (382, 'Scrubbie - Scotchbrite Hand Pad', 90);
insert into productos (id, producto, precio) values (383, 'Lemonade - Kiwi, 591 Ml', 74);
insert into productos (id, producto, precio) values (384, 'Sobe - Berry Energy', 37);
insert into productos (id, producto, precio) values (385, 'Puree - Pear', 24);
insert into productos (id, producto, precio) values (386, 'Salmon - Atlantic, No Skin', 2);
insert into productos (id, producto, precio) values (387, 'Lettuce - Treviso', 74);
insert into productos (id, producto, precio) values (388, 'Venison - Liver', 93);
insert into productos (id, producto, precio) values (389, 'Halibut - Steaks', 4);
insert into productos (id, producto, precio) values (390, 'Juice - Apple 284ml', 20);
insert into productos (id, producto, precio) values (391, 'Sour Puss Raspberry', 83);
insert into productos (id, producto, precio) values (392, 'Chef Hat 20cm', 33);
insert into productos (id, producto, precio) values (393, 'Bagelers', 22);
insert into productos (id, producto, precio) values (394, 'Crawfish', 26);
insert into productos (id, producto, precio) values (395, 'Veal - Insides, Grains', 74);
insert into productos (id, producto, precio) values (396, 'Pork - Sausage, Medium', 49);
insert into productos (id, producto, precio) values (397, 'Longos - Greek Salad', 36);
insert into productos (id, producto, precio) values (398, 'Napkin White', 33);
insert into productos (id, producto, precio) values (399, 'Wine - George Duboeuf Rose', 23);
insert into productos (id, producto, precio) values (400, 'Honey - Lavender', 3);
insert into productos (id, producto, precio) values (401, 'Soup - Boston Clam Chowder', 94);
insert into productos (id, producto, precio) values (402, 'Paste - Black Olive', 9);
insert into productos (id, producto, precio) values (403, 'Vermouth - Sweet, Cinzano', 36);
insert into productos (id, producto, precio) values (404, 'Soy Protein', 56);
insert into productos (id, producto, precio) values (405, 'Sugar - Brown', 60);
insert into productos (id, producto, precio) values (406, 'Tea - Jasmin Green', 10);
insert into productos (id, producto, precio) values (407, 'Ham - Smoked, Bone - In', 68);
insert into productos (id, producto, precio) values (408, 'Cheese - Camembert', 74);
insert into productos (id, producto, precio) values (409, 'Tomato - Peeled Italian Canned', 54);
insert into productos (id, producto, precio) values (410, 'Pasta - Lasagne, Fresh', 25);
insert into productos (id, producto, precio) values (411, 'Cheese - Brie, Cups 125g', 50);
insert into productos (id, producto, precio) values (412, 'Wine - Casablanca Valley', 64);
insert into productos (id, producto, precio) values (413, 'Food Colouring - Pink', 34);
insert into productos (id, producto, precio) values (414, 'Sobe - Berry Energy', 70);
insert into productos (id, producto, precio) values (415, 'Cookies - Oreo, 4 Pack', 22);
insert into productos (id, producto, precio) values (416, 'Syrup - Monin, Swiss Choclate', 58);
insert into productos (id, producto, precio) values (417, 'Cloves - Whole', 24);
insert into productos (id, producto, precio) values (418, 'Artichoke - Hearts, Canned', 56);
insert into productos (id, producto, precio) values (419, 'Sauce - Plum', 41);
insert into productos (id, producto, precio) values (420, 'Sauce - Ranch Dressing', 13);
insert into productos (id, producto, precio) values (421, 'Dehydrated Kelp Kombo', 3);
insert into productos (id, producto, precio) values (422, 'Kohlrabi', 76);
insert into productos (id, producto, precio) values (423, 'Bread - Italian Roll With Herbs', 3);
insert into productos (id, producto, precio) values (424, 'Grapefruit - White', 67);
insert into productos (id, producto, precio) values (425, 'Yogurt - Banana, 175 Gr', 33);
insert into productos (id, producto, precio) values (426, 'Tilapia - Fillets', 100);
insert into productos (id, producto, precio) values (427, 'Evaporated Milk - Skim', 88);
insert into productos (id, producto, precio) values (428, 'Beans - Navy, Dry', 11);
insert into productos (id, producto, precio) values (429, 'Chicken Breast Wing On', 6);
insert into productos (id, producto, precio) values (430, 'Cake - Dulce De Leche', 82);
insert into productos (id, producto, precio) values (431, 'Sausage - Liver', 71);
insert into productos (id, producto, precio) values (432, 'Ecolab - Balanced Fusion', 28);
insert into productos (id, producto, precio) values (433, 'Cheese - Brie', 45);
insert into productos (id, producto, precio) values (434, 'Melon - Watermelon Yellow', 32);
insert into productos (id, producto, precio) values (435, 'Juice Peach Nectar', 19);
insert into productos (id, producto, precio) values (436, 'Rye Special Old', 92);
insert into productos (id, producto, precio) values (437, 'Pan Grease', 1);
insert into productos (id, producto, precio) values (438, 'Syrup - Monin - Blue Curacao', 49);
insert into productos (id, producto, precio) values (439, 'Soup Campbells Turkey Veg.', 55);
insert into productos (id, producto, precio) values (440, 'Napkin - Beverge, White 2 - Ply', 18);
insert into productos (id, producto, precio) values (441, 'Flavouring - Orange', 55);
insert into productos (id, producto, precio) values (442, 'Bread - French Stick', 84);
insert into productos (id, producto, precio) values (443, 'Chicken - Whole Roasting', 92);
insert into productos (id, producto, precio) values (444, 'Cake - Cake Sheet Macaroon', 11);
insert into productos (id, producto, precio) values (445, 'Wine - Red, Antinori Santa', 88);
insert into productos (id, producto, precio) values (446, 'Sauce - Oyster', 15);
insert into productos (id, producto, precio) values (447, 'Amaretto', 79);
insert into productos (id, producto, precio) values (448, 'Flavouring Vanilla Artificial', 9);
insert into productos (id, producto, precio) values (449, 'Sprouts - Peppercress', 70);
insert into productos (id, producto, precio) values (450, 'Bagel - 12 Grain Preslice', 70);
insert into productos (id, producto, precio) values (451, 'Wine - Jaboulet Cotes Du Rhone', 92);
insert into productos (id, producto, precio) values (452, 'Soup Campbells - Tomato Bisque', 14);
insert into productos (id, producto, precio) values (453, 'Oil - Safflower', 46);
insert into productos (id, producto, precio) values (454, 'Parsnip', 83);
insert into productos (id, producto, precio) values (455, 'Vinegar - Red Wine', 81);
insert into productos (id, producto, precio) values (456, 'Table Cloth 90x90 Colour', 84);
insert into productos (id, producto, precio) values (457, 'Red Snapper - Fillet, Skin On', 19);
insert into productos (id, producto, precio) values (458, 'Pastry - Cherry Danish - Mini', 96);
insert into productos (id, producto, precio) values (459, 'Wine - Marlbourough Sauv Blanc', 45);
insert into productos (id, producto, precio) values (460, 'Veal - Chops, Split, Frenched', 40);
insert into productos (id, producto, precio) values (461, 'Pepper - Red Bell', 46);
insert into productos (id, producto, precio) values (462, 'Lidsoupcont Rp12dn', 3);
insert into productos (id, producto, precio) values (463, 'Beef Ground Medium', 100);
insert into productos (id, producto, precio) values (464, 'Icecream - Dibs', 25);
insert into productos (id, producto, precio) values (465, 'Initation Crab Meat', 40);
insert into productos (id, producto, precio) values (466, 'Soup Campbells Beef With Veg', 64);
insert into productos (id, producto, precio) values (467, 'Apple - Northern Spy', 63);
insert into productos (id, producto, precio) values (468, 'Mushroom - Crimini', 39);
insert into productos (id, producto, precio) values (469, 'Cookie Dough - Chunky', 94);
insert into productos (id, producto, precio) values (470, 'Beer - Maudite', 74);
insert into productos (id, producto, precio) values (471, 'Spic And Span All Purpose', 3);
insert into productos (id, producto, precio) values (472, 'Bread - Ciabatta Buns', 16);
insert into productos (id, producto, precio) values (473, 'Wine - Red, Gallo, Merlot', 61);
insert into productos (id, producto, precio) values (474, 'Lobster - Base', 48);
insert into productos (id, producto, precio) values (475, 'Lotus Rootlets - Canned', 94);
insert into productos (id, producto, precio) values (476, 'Wine - Saint - Bris 2002, Sauv', 96);
insert into productos (id, producto, precio) values (477, 'Wine - Red, Gamay Noir', 7);
insert into productos (id, producto, precio) values (478, 'Pork - Loin, Boneless', 18);
insert into productos (id, producto, precio) values (479, 'Steel Wool S.o.s', 36);
insert into productos (id, producto, precio) values (480, 'Apricots Fresh', 49);
insert into productos (id, producto, precio) values (481, 'Mint - Fresh', 97);
insert into productos (id, producto, precio) values (482, 'Juice - Grapefruit, 341 Ml', 33);
insert into productos (id, producto, precio) values (483, 'Cloves - Whole', 79);
insert into productos (id, producto, precio) values (484, 'Pie Pecan', 91);
insert into productos (id, producto, precio) values (485, 'Potatoes - Yukon Gold 5 Oz', 77);
insert into productos (id, producto, precio) values (486, 'Sauce - Roasted Red Pepper', 49);
insert into productos (id, producto, precio) values (487, 'Veal - Inside, Choice', 22);
insert into productos (id, producto, precio) values (488, 'Wine - Fino Tio Pepe Gonzalez', 5);
insert into productos (id, producto, precio) values (489, 'Juice - Orange', 94);
insert into productos (id, producto, precio) values (490, 'Brandy Cherry - Mcguinness', 17);
insert into productos (id, producto, precio) values (491, 'Sauce - Hollandaise', 46);
insert into productos (id, producto, precio) values (492, 'Soup - Campbells, Beef Barley', 76);
insert into productos (id, producto, precio) values (493, 'Pomello', 44);
insert into productos (id, producto, precio) values (494, 'Gelatine Leaves - Envelopes', 83);
insert into productos (id, producto, precio) values (495, 'Soup - Campbellschix Stew', 69);
insert into productos (id, producto, precio) values (496, 'Wine - White, Ej Gallo', 65);
insert into productos (id, producto, precio) values (497, 'Tray - 16in Rnd Blk', 27);
insert into productos (id, producto, precio) values (498, 'Anchovy Paste - 56 G Tube', 79);
insert into productos (id, producto, precio) values (499, 'Taro Leaves', 59);
insert into productos (id, producto, precio) values (500, 'Arrowroot', 16);
insert into productos (id, producto, precio) values (501, 'Bread - Pain Au Liat X12', 24);
insert into productos (id, producto, precio) values (502, 'Soap - Hand Soap', 37);
insert into productos (id, producto, precio) values (503, 'Fork - Plastic', 93);
insert into productos (id, producto, precio) values (504, 'Zucchini - Mini, Green', 83);
insert into productos (id, producto, precio) values (505, 'Cheese - Montery Jack', 65);
insert into productos (id, producto, precio) values (506, 'Rootbeer', 89);
insert into productos (id, producto, precio) values (507, 'Gatorade - Orange', 77);
insert into productos (id, producto, precio) values (508, 'Ham - Proscuitto', 53);
insert into productos (id, producto, precio) values (509, 'Soup - Campbells, Chix Gumbo', 75);
insert into productos (id, producto, precio) values (510, 'Pepper - Red Thai', 33);
insert into productos (id, producto, precio) values (511, 'Cakes Assorted', 19);
insert into productos (id, producto, precio) values (512, 'Crackers - Melba Toast', 29);
insert into productos (id, producto, precio) values (513, 'Squash - Sunburst', 21);
insert into productos (id, producto, precio) values (514, 'Salmon - Whole, 4 - 6 Pounds', 27);
insert into productos (id, producto, precio) values (515, 'Chips - Potato Jalapeno', 96);
insert into productos (id, producto, precio) values (516, 'Island Oasis - Mango Daiquiri', 14);
insert into productos (id, producto, precio) values (517, 'Artichoke - Hearts, Canned', 28);
insert into productos (id, producto, precio) values (518, 'Mayonnaise', 67);
insert into productos (id, producto, precio) values (519, 'Wine - Domaine Boyar Royal', 91);
insert into productos (id, producto, precio) values (520, 'V8 - Berry Blend', 47);
insert into productos (id, producto, precio) values (521, 'Bagel - Plain', 37);
insert into productos (id, producto, precio) values (522, 'Mushroom - Enoki, Dry', 42);
insert into productos (id, producto, precio) values (523, 'Oil - Coconut', 83);
insert into productos (id, producto, precio) values (524, 'Clams - Canned', 60);
insert into productos (id, producto, precio) values (525, 'Pear - Halves', 75);
insert into productos (id, producto, precio) values (526, 'Snapple - Mango Maddness', 95);
insert into productos (id, producto, precio) values (527, 'Oil - Olive', 70);
insert into productos (id, producto, precio) values (528, 'Grapefruit - White', 50);
insert into productos (id, producto, precio) values (529, 'Cheese - Havarti, Roasted Garlic', 42);
insert into productos (id, producto, precio) values (530, 'Seedlings - Clamshell', 69);
insert into productos (id, producto, precio) values (531, 'Bag Stand', 10);
insert into productos (id, producto, precio) values (532, 'Cake - Night And Day Choclate', 74);
insert into productos (id, producto, precio) values (533, 'Cassis', 46);
insert into productos (id, producto, precio) values (534, 'Seedlings - Buckwheat, Organic', 70);
insert into productos (id, producto, precio) values (535, 'Muffin - Mix - Mango Sour Cherry', 98);
insert into productos (id, producto, precio) values (536, 'Water - Perrier', 83);
insert into productos (id, producto, precio) values (537, 'Mortadella', 19);
insert into productos (id, producto, precio) values (538, 'Oil - Avocado', 75);
insert into productos (id, producto, precio) values (539, 'Aspic - Light', 66);
insert into productos (id, producto, precio) values (540, 'Beef Cheek Fresh', 85);
insert into productos (id, producto, precio) values (541, 'Cod - Black Whole Fillet', 61);
insert into productos (id, producto, precio) values (542, 'Wine - Fume Blanc Fetzer', 28);
insert into productos (id, producto, precio) values (543, 'Lemonade - Kiwi, 591 Ml', 69);
insert into productos (id, producto, precio) values (544, 'Raspberries - Frozen', 42);
insert into productos (id, producto, precio) values (545, 'Pasta - Linguini, Dry', 66);
insert into productos (id, producto, precio) values (546, 'Lamb - Leg, Diced', 57);
insert into productos (id, producto, precio) values (547, 'Chickensplit Half', 29);
insert into productos (id, producto, precio) values (548, 'Wine - Vovray Sec Domaine Huet', 60);
insert into productos (id, producto, precio) values (549, 'Onion - Dried', 73);
insert into productos (id, producto, precio) values (550, 'Bread - Sour Sticks With Onion', 63);
insert into productos (id, producto, precio) values (551, 'Skewers - Bamboo', 8);
insert into productos (id, producto, precio) values (552, 'Cup - 3.5oz, Foam', 45);
insert into productos (id, producto, precio) values (553, 'Pepper - Jalapeno', 63);
insert into productos (id, producto, precio) values (554, 'Coffee - Decafenated', 4);
insert into productos (id, producto, precio) values (555, 'Artichoke - Bottom, Canned', 80);
insert into productos (id, producto, precio) values (556, 'Lamb - Leg, Diced', 37);
insert into productos (id, producto, precio) values (557, 'Potatoes - Fingerling 4 Oz', 77);
insert into productos (id, producto, precio) values (558, 'Melon - Honey Dew', 73);
insert into productos (id, producto, precio) values (559, 'Cake - Pancake', 99);
insert into productos (id, producto, precio) values (560, 'Rosemary - Primerba, Paste', 17);
insert into productos (id, producto, precio) values (561, 'Sobe - Orange Carrot', 4);
insert into productos (id, producto, precio) values (562, 'Table Cloth 53x53 White', 33);
insert into productos (id, producto, precio) values (563, 'Wine - Puligny Montrachet A.', 92);
insert into productos (id, producto, precio) values (564, 'Sauce - Bernaise, Mix', 45);
insert into productos (id, producto, precio) values (565, 'Soap - Mr.clean Floor Soap', 21);
insert into productos (id, producto, precio) values (566, 'Table Cloth 54x54 White', 69);
insert into productos (id, producto, precio) values (567, 'Flounder - Fresh', 75);
insert into productos (id, producto, precio) values (568, 'Trout - Hot Smkd, Dbl Fillet', 91);
insert into productos (id, producto, precio) values (569, 'Flavouring - Rum', 19);
insert into productos (id, producto, precio) values (570, 'Sardines', 67);
insert into productos (id, producto, precio) values (571, 'Broom - Corn', 59);
insert into productos (id, producto, precio) values (572, 'Everfresh Products', 90);
insert into productos (id, producto, precio) values (573, 'Sauce - Fish 25 Ozf Bottle', 16);
insert into productos (id, producto, precio) values (574, 'Juice - Pineapple, 341 Ml', 20);
insert into productos (id, producto, precio) values (575, 'Sauce - Plum', 10);
insert into productos (id, producto, precio) values (576, 'Rum - Coconut, Malibu', 85);
insert into productos (id, producto, precio) values (577, 'Truffle - Whole Black Peeled', 52);
insert into productos (id, producto, precio) values (578, 'Crab - Dungeness, Whole', 15);
insert into productos (id, producto, precio) values (579, 'Wine - Red, Cabernet Merlot', 2);
insert into productos (id, producto, precio) values (580, 'Pork - Belly Fresh', 1);
insert into productos (id, producto, precio) values (581, 'Wheat - Soft Kernal Of Wheat', 44);
insert into productos (id, producto, precio) values (582, 'Flour - Fast / Rapid', 94);
insert into productos (id, producto, precio) values (583, 'Sugar Thermometer', 42);
insert into productos (id, producto, precio) values (584, 'Compound - Raspberry', 81);
insert into productos (id, producto, precio) values (585, 'Nut - Pistachio, Shelled', 44);
insert into productos (id, producto, precio) values (586, 'Squash - Butternut', 25);
insert into productos (id, producto, precio) values (587, 'Table Cloth 91x91 Colour', 20);
insert into productos (id, producto, precio) values (588, 'Barramundi', 20);
insert into productos (id, producto, precio) values (589, 'Noodles - Steamed Chow Mein', 90);
insert into productos (id, producto, precio) values (590, 'Cumin - Ground', 99);
insert into productos (id, producto, precio) values (591, 'Coffee - Beans, Whole', 17);
insert into productos (id, producto, precio) values (592, 'Coffee Cup 16oz Foam', 39);
insert into productos (id, producto, precio) values (593, 'Flavouring Vanilla Artificial', 36);
insert into productos (id, producto, precio) values (594, 'Soup - Chicken And Wild Rice', 95);
insert into productos (id, producto, precio) values (595, 'Worcestershire Sauce', 27);
insert into productos (id, producto, precio) values (596, 'Wiberg Super Cure', 72);
insert into productos (id, producto, precio) values (597, 'Huck Towels White', 49);
insert into productos (id, producto, precio) values (598, 'Tofu - Firm', 72);
insert into productos (id, producto, precio) values (599, 'Pear - Halves', 89);
insert into productos (id, producto, precio) values (600, 'Tart Shells - Savory, 4', 76);
insert into productos (id, producto, precio) values (601, 'Wine - Blue Nun Qualitatswein', 81);
insert into productos (id, producto, precio) values (602, 'Paper Towel Touchless', 96);
insert into productos (id, producto, precio) values (603, 'Nantucket Apple Juice', 54);
insert into productos (id, producto, precio) values (604, 'Lettuce - Romaine, Heart', 9);
insert into productos (id, producto, precio) values (605, 'Soup - Boston Clam Chowder', 10);
insert into productos (id, producto, precio) values (606, 'Artichokes - Jerusalem', 9);
insert into productos (id, producto, precio) values (607, 'Container - Clear 16 Oz', 17);
insert into productos (id, producto, precio) values (608, 'Turnip - Mini', 34);
insert into productos (id, producto, precio) values (609, 'Wine - Chateau Timberlay', 100);
insert into productos (id, producto, precio) values (610, 'Calypso - Pineapple Passion', 66);
insert into productos (id, producto, precio) values (611, 'Fish - Scallops, Cold Smoked', 25);
insert into productos (id, producto, precio) values (612, 'Turkey Tenderloin Frozen', 96);
insert into productos (id, producto, precio) values (613, 'Lamb Rack - Ontario', 98);
insert into productos (id, producto, precio) values (614, 'Mint - Fresh', 92);
insert into productos (id, producto, precio) values (615, 'Assorted Desserts', 82);
insert into productos (id, producto, precio) values (616, 'Lobster - Baby, Boiled', 41);
insert into productos (id, producto, precio) values (617, 'Cheese - Cheddarsliced', 28);
insert into productos (id, producto, precio) values (618, 'The Pop Shoppe - Root Beer', 71);
insert into productos (id, producto, precio) values (619, 'Shrimp - Black Tiger 13/15', 42);
insert into productos (id, producto, precio) values (620, 'Sultanas', 72);
insert into productos (id, producto, precio) values (621, 'Cinnamon Rolls', 46);
insert into productos (id, producto, precio) values (622, 'Bonito Flakes - Toku Katsuo', 58);
insert into productos (id, producto, precio) values (623, 'Rum - Light, Captain Morgan', 90);
insert into productos (id, producto, precio) values (624, 'Galliano', 99);
insert into productos (id, producto, precio) values (625, 'Jolt Cola', 42);
insert into productos (id, producto, precio) values (626, 'Pastry - Cheese Baked Scones', 43);
insert into productos (id, producto, precio) values (627, 'Soup Campbells Turkey Veg.', 26);
insert into productos (id, producto, precio) values (628, 'Sage Ground Wiberg', 18);
insert into productos (id, producto, precio) values (629, 'Heavy Duty Dust Pan', 54);
insert into productos (id, producto, precio) values (630, 'Puree - Strawberry', 81);
insert into productos (id, producto, precio) values (631, 'Split Peas - Green, Dry', 96);
insert into productos (id, producto, precio) values (632, 'Bananas', 95);
insert into productos (id, producto, precio) values (633, 'Flour - So Mix Cake White', 92);
insert into productos (id, producto, precio) values (634, 'Tea Peppermint', 1);
insert into productos (id, producto, precio) values (635, 'Toamtoes 6x7 Select', 100);
insert into productos (id, producto, precio) values (636, 'Chicken - Tenderloin', 27);
insert into productos (id, producto, precio) values (637, 'Roe - White Fish', 37);
insert into productos (id, producto, precio) values (638, 'Wine - Puligny Montrachet A.', 54);
insert into productos (id, producto, precio) values (639, 'Cream - 35%', 90);
insert into productos (id, producto, precio) values (640, 'Tomatillo', 82);
insert into productos (id, producto, precio) values (641, 'Tomato - Tricolor Cherry', 89);
insert into productos (id, producto, precio) values (642, 'Doilies - 5, Paper', 72);
insert into productos (id, producto, precio) values (643, 'Wine - Remy Pannier Rose', 73);
insert into productos (id, producto, precio) values (644, 'Higashimaru Usukuchi Soy', 74);
insert into productos (id, producto, precio) values (645, 'Curry Paste - Green Masala', 36);
insert into productos (id, producto, precio) values (646, 'Teriyaki Sauce', 47);
insert into productos (id, producto, precio) values (647, 'Beans - Fine', 9);
insert into productos (id, producto, precio) values (648, 'Cheese - Asiago', 45);
insert into productos (id, producto, precio) values (649, 'Carbonated Water - Blackcherry', 89);
insert into productos (id, producto, precio) values (650, 'Bread - Bagels, Mini', 55);
insert into productos (id, producto, precio) values (651, 'Soup - Campbells, Minestrone', 53);
insert into productos (id, producto, precio) values (652, 'Wine - Valpolicella Masi', 1);
insert into productos (id, producto, precio) values (653, 'Breakfast Quesadillas', 50);
insert into productos (id, producto, precio) values (654, 'Nantucket Orange Juice', 1);
insert into productos (id, producto, precio) values (655, 'Spice - Chili Powder Mexican', 83);
insert into productos (id, producto, precio) values (656, 'Isomalt', 28);
insert into productos (id, producto, precio) values (657, 'Icecream - Dibs', 45);
insert into productos (id, producto, precio) values (658, 'Cookie Chocolate Chip With', 99);
insert into productos (id, producto, precio) values (659, 'Veal - Knuckle', 60);
insert into productos (id, producto, precio) values (660, 'Kohlrabi', 28);
insert into productos (id, producto, precio) values (661, 'Pop Shoppe Cream Soda', 10);
insert into productos (id, producto, precio) values (662, 'Orange - Tangerine', 10);
insert into productos (id, producto, precio) values (663, 'Cheese - Asiago', 94);
insert into productos (id, producto, precio) values (664, 'Creme De Cacao White', 19);
insert into productos (id, producto, precio) values (665, 'Bagel - Whole White Sesame', 99);
insert into productos (id, producto, precio) values (666, 'Salt And Pepper Mix - Black', 16);
insert into productos (id, producto, precio) values (667, 'Jameson Irish Whiskey', 22);
insert into productos (id, producto, precio) values (668, 'Bread - Granary Small Pull', 83);
insert into productos (id, producto, precio) values (669, 'Vaccum Bag - 14x20', 35);
insert into productos (id, producto, precio) values (670, 'Puree - Pear', 98);
insert into productos (id, producto, precio) values (671, 'Dry Ice', 39);
insert into productos (id, producto, precio) values (672, 'Apron', 25);
insert into productos (id, producto, precio) values (673, 'Dehydrated Kelp Kombo', 6);
insert into productos (id, producto, precio) values (674, 'Ostrich - Fan Fillet', 43);
insert into productos (id, producto, precio) values (675, 'Mushroom - Portebello', 42);
insert into productos (id, producto, precio) values (676, 'Beef - Cooked, Corned', 46);
insert into productos (id, producto, precio) values (677, 'Greens Mustard', 5);
insert into productos (id, producto, precio) values (678, 'Neckerchief Blck', 64);
insert into productos (id, producto, precio) values (679, 'Pepper - Pablano', 6);
insert into productos (id, producto, precio) values (680, 'Kiwi Gold Zespri', 85);
insert into productos (id, producto, precio) values (681, 'Longos - Chicken Curried', 38);
insert into productos (id, producto, precio) values (682, 'Pork - Backfat', 70);
insert into productos (id, producto, precio) values (683, 'Pork - Loin, Bone - In', 15);
insert into productos (id, producto, precio) values (684, 'Berry Brulee', 31);
insert into productos (id, producto, precio) values (685, 'Bread Base - Toscano', 90);
insert into productos (id, producto, precio) values (686, 'Dried Cranberries', 31);
insert into productos (id, producto, precio) values (687, 'Mushroom - Crimini', 49);
insert into productos (id, producto, precio) values (688, 'Bacardi Limon', 43);
insert into productos (id, producto, precio) values (689, 'Stock - Chicken, White', 68);
insert into productos (id, producto, precio) values (690, 'Oil - Truffle, Black', 47);
insert into productos (id, producto, precio) values (691, 'Cheese - Le Cheve Noir', 66);
insert into productos (id, producto, precio) values (692, 'Crackers - Melba Toast', 61);
insert into productos (id, producto, precio) values (693, 'Clams - Canned', 26);
insert into productos (id, producto, precio) values (694, 'Straw - Regular', 76);
insert into productos (id, producto, precio) values (695, 'Mushroom - Morels, Dry', 50);
insert into productos (id, producto, precio) values (696, 'Lamb - Sausage Casings', 27);
insert into productos (id, producto, precio) values (697, 'Muffin - Blueberry Individual', 28);
insert into productos (id, producto, precio) values (698, 'Sauce - Soy Low Sodium - 3.87l', 40);
insert into productos (id, producto, precio) values (699, 'Coffee - Dark Roast', 99);
insert into productos (id, producto, precio) values (700, 'Pike - Frozen Fillet', 100);
insert into productos (id, producto, precio) values (701, 'Oregano - Fresh', 89);
insert into productos (id, producto, precio) values (702, 'Cardamon Seed / Pod', 29);
insert into productos (id, producto, precio) values (703, 'Potatoes - Mini White 3 Oz', 33);
insert into productos (id, producto, precio) values (704, 'Ecolab - Medallion', 48);
insert into productos (id, producto, precio) values (705, 'Pants Custom Dry Clean', 91);
insert into productos (id, producto, precio) values (706, 'Nut - Macadamia', 80);
insert into productos (id, producto, precio) values (707, 'Crackers - Trio', 65);
insert into productos (id, producto, precio) values (708, 'Dragon Fruit', 90);
insert into productos (id, producto, precio) values (709, 'Lemonade - Island Tea, 591 Ml', 33);
insert into productos (id, producto, precio) values (710, 'Ice Cream - Super Sandwich', 39);
insert into productos (id, producto, precio) values (711, 'Flour - Buckwheat, Dark', 73);
insert into productos (id, producto, precio) values (712, 'Limes', 75);
insert into productos (id, producto, precio) values (713, 'Soup - Campbells', 75);
insert into productos (id, producto, precio) values (714, 'Venison - Liver', 8);
insert into productos (id, producto, precio) values (715, 'Basil - Thai', 44);
insert into productos (id, producto, precio) values (716, 'Wine - Segura Viudas Aria Brut', 72);
insert into productos (id, producto, precio) values (717, 'Wine - White, Pelee Island', 28);
insert into productos (id, producto, precio) values (718, 'Flour Dark Rye', 77);
insert into productos (id, producto, precio) values (719, 'Chips - Potato Jalapeno', 67);
insert into productos (id, producto, precio) values (720, 'Mushroom - Morel Frozen', 96);
insert into productos (id, producto, precio) values (721, 'Bread - Italian Roll With Herbs', 51);
insert into productos (id, producto, precio) values (722, 'Muffin Batt - Ban Dream Zero', 12);
insert into productos (id, producto, precio) values (723, 'Island Oasis - Lemonade', 55);
insert into productos (id, producto, precio) values (724, 'Yogurt - Strawberry, 175 Gr', 16);
insert into productos (id, producto, precio) values (725, 'Beef - Tongue, Fresh', 18);
insert into productos (id, producto, precio) values (726, 'Jam - Apricot', 74);
insert into productos (id, producto, precio) values (727, 'Bread - Multigrain Oval', 88);
insert into productos (id, producto, precio) values (728, 'Meldea Green Tea Liquor', 84);
insert into productos (id, producto, precio) values (729, 'Gatorade - Fruit Punch', 85);
insert into productos (id, producto, precio) values (730, 'Goat - Whole Cut', 90);
insert into productos (id, producto, precio) values (731, 'Food Colouring - Blue', 24);
insert into productos (id, producto, precio) values (732, 'Grapefruit - White', 19);
insert into productos (id, producto, precio) values (733, 'Icecream Cone - Areo Chocolate', 36);
insert into productos (id, producto, precio) values (734, 'Pepper - Red, Finger Hot', 72);
insert into productos (id, producto, precio) values (735, 'Muffin - Mix - Strawberry Rhubarb', 56);
insert into productos (id, producto, precio) values (736, 'Pasta - Angel Hair', 23);
insert into productos (id, producto, precio) values (737, 'Scallops - 20/30', 12);
insert into productos (id, producto, precio) values (738, 'Tomatoes - Orange', 39);
insert into productos (id, producto, precio) values (739, 'Rice Wine - Aji Mirin', 37);
insert into productos (id, producto, precio) values (740, 'Bread - Bistro White', 100);
insert into productos (id, producto, precio) values (741, 'Wine - Domaine Boyar Royal', 61);
insert into productos (id, producto, precio) values (742, 'Sauce - Balsamic Viniagrette', 91);
insert into productos (id, producto, precio) values (743, 'Calypso - Lemonade', 98);
insert into productos (id, producto, precio) values (744, 'Bag Clear 10 Lb', 91);
insert into productos (id, producto, precio) values (745, 'Pork - Loin, Bone - In', 79);
insert into productos (id, producto, precio) values (746, 'Oregano - Fresh', 100);
insert into productos (id, producto, precio) values (747, 'Sparkling Wine - Rose, Freixenet', 63);
insert into productos (id, producto, precio) values (748, 'Sherry - Dry', 13);
insert into productos (id, producto, precio) values (749, 'Tart - Pecan Butter Squares', 17);
insert into productos (id, producto, precio) values (750, 'Pork - Side Ribs', 48);
insert into productos (id, producto, precio) values (751, 'Grapes - Black', 62);
insert into productos (id, producto, precio) values (752, 'Pail With Metal Handle 16l White', 28);
insert into productos (id, producto, precio) values (753, 'Pasta - Fettuccine, Dry', 83);
insert into productos (id, producto, precio) values (754, 'Muffin Batt - Carrot Spice', 85);
insert into productos (id, producto, precio) values (755, 'Mince Meat - Filling', 35);
insert into productos (id, producto, precio) values (756, 'Beer - True North Strong Ale', 76);
insert into productos (id, producto, precio) values (757, 'Wine - Fat Bastard Merlot', 79);
insert into productos (id, producto, precio) values (758, 'Cheese - Cheddar, Old White', 26);
insert into productos (id, producto, precio) values (759, 'Yogurt - Cherry, 175 Gr', 93);
insert into productos (id, producto, precio) values (760, 'Pie Box - Cello Window 2.5', 99);
insert into productos (id, producto, precio) values (761, 'Ham - Cooked Italian', 83);
insert into productos (id, producto, precio) values (762, 'Chicken - White Meat With Tender', 100);
insert into productos (id, producto, precio) values (763, 'Lobster - Tail 6 Oz', 66);
insert into productos (id, producto, precio) values (764, 'Contreau', 1);
insert into productos (id, producto, precio) values (765, 'Oil - Canola', 84);
insert into productos (id, producto, precio) values (766, 'Bar Special K', 50);
insert into productos (id, producto, precio) values (767, 'Marjoram - Dried, Rubbed', 78);
insert into productos (id, producto, precio) values (768, 'Gelatine Leaves - Bulk', 10);
insert into productos (id, producto, precio) values (769, 'Chervil - Fresh', 22);
insert into productos (id, producto, precio) values (770, 'Beef Wellington', 20);
insert into productos (id, producto, precio) values (771, 'Bread - Raisin Walnut Oval', 70);
insert into productos (id, producto, precio) values (772, 'Pail - 4l White, With Handle', 19);
insert into productos (id, producto, precio) values (773, 'Crab - Meat Combo', 6);
insert into productos (id, producto, precio) values (774, 'Bar Mix - Pina Colada, 355 Ml', 51);
insert into productos (id, producto, precio) values (775, 'Jerusalem Artichoke', 7);
insert into productos (id, producto, precio) values (776, 'Pepper - Chili Powder', 15);
insert into productos (id, producto, precio) values (777, 'Napkin - Beverge, White 2 - Ply', 32);
insert into productos (id, producto, precio) values (778, 'Wine - Remy Pannier Rose', 72);
insert into productos (id, producto, precio) values (779, 'Capon - Whole', 43);
insert into productos (id, producto, precio) values (780, 'Vinegar - Raspberry', 45);
insert into productos (id, producto, precio) values (781, 'Cookies - Englishbay Wht', 14);
insert into productos (id, producto, precio) values (782, 'Glycerine', 32);
insert into productos (id, producto, precio) values (783, 'Nut - Pumpkin Seeds', 62);
insert into productos (id, producto, precio) values (784, 'Veal - Shank, Pieces', 33);
insert into productos (id, producto, precio) values (785, 'Salt - Seasoned', 71);
insert into productos (id, producto, precio) values (786, 'Peas Snow', 40);
insert into productos (id, producto, precio) values (787, 'Wine - Montecillo Rioja Crianza', 99);
insert into productos (id, producto, precio) values (788, 'Mints - Striped Red', 60);
insert into productos (id, producto, precio) values (789, 'Beef - Tongue, Fresh', 61);
insert into productos (id, producto, precio) values (790, 'Beef - Rib Roast, Capless', 12);
insert into productos (id, producto, precio) values (791, 'Bread - Assorted Rolls', 22);
insert into productos (id, producto, precio) values (792, 'Cheese - Taleggio D.o.p.', 52);
insert into productos (id, producto, precio) values (793, 'Rye Special Old', 85);
insert into productos (id, producto, precio) values (794, 'Fruit Salad Deluxe', 5);
insert into productos (id, producto, precio) values (795, 'Bread - French Stick', 68);
insert into productos (id, producto, precio) values (796, 'Container Clear 8 Oz', 39);
insert into productos (id, producto, precio) values (797, 'Laundry - Bag Cloth', 30);
insert into productos (id, producto, precio) values (798, 'Sprouts - Bean', 67);
insert into productos (id, producto, precio) values (799, 'Mini - Vol Au Vents', 65);
insert into productos (id, producto, precio) values (800, 'Swordfish Loin Portions', 53);
insert into productos (id, producto, precio) values (801, 'Wine - Charddonnay Errazuriz', 92);
insert into productos (id, producto, precio) values (802, 'Potatoes - Yukon Gold 5 Oz', 96);
insert into productos (id, producto, precio) values (803, 'Wine - Pinot Grigio Collavini', 34);
insert into productos (id, producto, precio) values (804, 'Mustard - Individual Pkg', 40);
insert into productos (id, producto, precio) values (805, 'Caviar - Salmon', 28);
insert into productos (id, producto, precio) values (806, 'Baking Powder', 85);
insert into productos (id, producto, precio) values (807, 'Pastry - Butterscotch Baked', 82);
insert into productos (id, producto, precio) values (808, 'Vinegar - Cider', 10);
insert into productos (id, producto, precio) values (809, 'Wine - Sake', 49);
insert into productos (id, producto, precio) values (810, 'Cake - Box Window 10x10x2.5', 82);
insert into productos (id, producto, precio) values (811, 'Ice Cream - Super Sandwich', 49);
insert into productos (id, producto, precio) values (812, 'Chips - Doritos', 39);
insert into productos (id, producto, precio) values (813, 'Beer - Labatt Blue', 12);
insert into productos (id, producto, precio) values (814, 'Syrup - Chocolate', 84);
insert into productos (id, producto, precio) values (815, 'Mikes Hard Lemonade', 18);
insert into productos (id, producto, precio) values (816, 'Spinach - Packaged', 38);
insert into productos (id, producto, precio) values (817, 'Hold Up Tool Storage Rack', 40);
insert into productos (id, producto, precio) values (818, 'Wine - Chardonnay Mondavi', 32);
insert into productos (id, producto, precio) values (819, 'Cassis', 29);
insert into productos (id, producto, precio) values (820, 'Edible Flower - Mixed', 97);
insert into productos (id, producto, precio) values (821, 'Soup - Campbells - Tomato', 50);
insert into productos (id, producto, precio) values (822, 'Salmon - Smoked, Sliced', 59);
insert into productos (id, producto, precio) values (823, 'Wine - Conde De Valdemar', 97);
insert into productos (id, producto, precio) values (824, 'Juice - Clamato, 341 Ml', 9);
insert into productos (id, producto, precio) values (825, 'Langers - Ruby Red Grapfruit', 52);
insert into productos (id, producto, precio) values (826, 'Plate Pie Foil', 4);
insert into productos (id, producto, precio) values (827, 'Beef - Kindney, Whole', 61);
insert into productos (id, producto, precio) values (828, 'Kellogs All Bran Bars', 78);
insert into productos (id, producto, precio) values (829, 'Bagelers - Cinn / Brown Sugar', 67);
insert into productos (id, producto, precio) values (830, 'Longos - Burritos', 71);
insert into productos (id, producto, precio) values (831, 'Brandy - Orange, Mc Guiness', 78);
insert into productos (id, producto, precio) values (832, 'Wine - Fontanafredda Barolo', 45);
insert into productos (id, producto, precio) values (833, 'Pastry - Raisin Muffin - Mini', 61);
insert into productos (id, producto, precio) values (834, 'Ranchero - Primerba, Paste', 37);
insert into productos (id, producto, precio) values (835, 'Sprite - 355 Ml', 7);
insert into productos (id, producto, precio) values (836, 'Shrimp - Black Tiger 26/30', 23);
insert into productos (id, producto, precio) values (837, 'Flower - Dish Garden', 21);
insert into productos (id, producto, precio) values (838, 'Wine - Port Late Bottled Vintage', 99);
insert into productos (id, producto, precio) values (839, 'Sprite, Diet - 355ml', 70);
insert into productos (id, producto, precio) values (840, 'Pasta - Penne, Lisce, Dry', 1);
insert into productos (id, producto, precio) values (841, 'Pepper - Cayenne', 98);
insert into productos (id, producto, precio) values (842, 'Ham - Procutinni', 19);
insert into productos (id, producto, precio) values (843, 'Peach - Fresh', 51);
insert into productos (id, producto, precio) values (844, 'Syrup - Monin - Granny Smith', 63);
insert into productos (id, producto, precio) values (845, 'Creme De Cacao White', 57);
insert into productos (id, producto, precio) values (846, 'Fish - Atlantic Salmon, Cold', 89);
insert into productos (id, producto, precio) values (847, 'Broccoli - Fresh', 26);
insert into productos (id, producto, precio) values (848, 'Cheese - Gouda Smoked', 63);
insert into productos (id, producto, precio) values (849, 'Cherries - Frozen', 70);
insert into productos (id, producto, precio) values (850, 'Cocoa Butter', 63);
insert into productos (id, producto, precio) values (851, 'Yeast Dry - Fermipan', 35);
insert into productos (id, producto, precio) values (852, 'Beef - Short Ribs', 85);
insert into productos (id, producto, precio) values (853, 'Wine - Blue Nun Qualitatswein', 100);
insert into productos (id, producto, precio) values (854, 'Bread - French Stick', 99);
insert into productos (id, producto, precio) values (855, 'Waffle Stix', 79);
insert into productos (id, producto, precio) values (856, 'Pepper - Orange', 21);
insert into productos (id, producto, precio) values (857, 'Savory', 66);
insert into productos (id, producto, precio) values (858, 'Sauerkraut', 63);
insert into productos (id, producto, precio) values (859, 'Gatorade - Xfactor Berry', 23);
insert into productos (id, producto, precio) values (860, 'Cheese Cloth No 60', 28);
insert into productos (id, producto, precio) values (861, 'Chip - Potato Dill Pickle', 96);
insert into productos (id, producto, precio) values (862, 'Wine - Prem Select Charddonany', 42);
insert into productos (id, producto, precio) values (863, 'Pickles - Gherkins', 7);
insert into productos (id, producto, precio) values (864, 'Pork - Bacon, Double Smoked', 48);
insert into productos (id, producto, precio) values (865, 'Wine - Fino Tio Pepe Gonzalez', 95);
insert into productos (id, producto, precio) values (866, 'Flour - Teff', 25);
insert into productos (id, producto, precio) values (867, 'Zucchini - Mini, Green', 70);
insert into productos (id, producto, precio) values (868, 'Compound - Orange', 37);
insert into productos (id, producto, precio) values (869, 'Pastry - Lemon Danish - Mini', 90);
insert into productos (id, producto, precio) values (870, 'Cup - 4oz Translucent', 70);
insert into productos (id, producto, precio) values (871, 'Potato - Sweet', 69);
insert into productos (id, producto, precio) values (872, 'Crab - Meat Combo', 65);
insert into productos (id, producto, precio) values (873, 'Green Tea Refresher', 64);
insert into productos (id, producto, precio) values (874, 'Garlic - Primerba, Paste', 57);
insert into productos (id, producto, precio) values (875, 'Greens Mustard', 74);
insert into productos (id, producto, precio) values (876, 'Mayonnaise - Individual Pkg', 27);
insert into productos (id, producto, precio) values (877, 'Bacardi Raspberry', 1);
insert into productos (id, producto, precio) values (878, 'Water - San Pellegrino', 93);
insert into productos (id, producto, precio) values (879, 'Lidsoupcont Rp12dn', 99);
insert into productos (id, producto, precio) values (880, 'Butter Ripple - Phillips', 60);
insert into productos (id, producto, precio) values (881, 'Butter - Pod', 94);
insert into productos (id, producto, precio) values (882, 'Nut - Pecan, Halves', 95);
insert into productos (id, producto, precio) values (883, 'Coffee - Colombian, Portioned', 63);
insert into productos (id, producto, precio) values (884, 'Lemon Balm - Fresh', 88);
insert into productos (id, producto, precio) values (885, 'Pork - Belly Fresh', 64);
insert into productos (id, producto, precio) values (886, 'Soup - Knorr, Country Bean', 51);
insert into productos (id, producto, precio) values (887, 'Bread - White Epi Baguette', 24);
insert into productos (id, producto, precio) values (888, 'Cheese - Sheep Milk', 5);
insert into productos (id, producto, precio) values (889, 'Wine - Red, Lurton Merlot De', 38);
insert into productos (id, producto, precio) values (890, 'Veal - Ground', 14);
insert into productos (id, producto, precio) values (891, 'Cheese - Camembert', 21);
insert into productos (id, producto, precio) values (892, 'Wine - Wyndham Estate Bin 777', 9);
insert into productos (id, producto, precio) values (893, 'Spring Roll Wrappers', 43);
insert into productos (id, producto, precio) values (894, 'Yeast Dry - Fermipan', 63);
insert into productos (id, producto, precio) values (895, 'Cheese - Blue', 79);
insert into productos (id, producto, precio) values (896, 'Edible Flower - Mixed', 51);
insert into productos (id, producto, precio) values (897, 'Muffin - Bran Ind Wrpd', 81);
insert into productos (id, producto, precio) values (898, 'Pepper - Orange', 56);
insert into productos (id, producto, precio) values (899, 'Island Oasis - Banana Daiquiri', 67);
insert into productos (id, producto, precio) values (900, 'Beer - Pilsner Urquell', 97);
insert into productos (id, producto, precio) values (901, 'Crab - Soft Shell', 91);
insert into productos (id, producto, precio) values (902, 'Chilli Paste, Sambal Oelek', 31);
insert into productos (id, producto, precio) values (903, 'Halibut - Steaks', 78);
insert into productos (id, producto, precio) values (904, 'Compound - Rum', 30);
insert into productos (id, producto, precio) values (905, 'Beer - Steamwhistle', 90);
insert into productos (id, producto, precio) values (906, 'Shrimp - Black Tiger 8 - 12', 17);
insert into productos (id, producto, precio) values (907, 'Neckerchief Blck', 1);
insert into productos (id, producto, precio) values (908, 'Flower - Daisies', 27);
insert into productos (id, producto, precio) values (909, 'Contreau', 30);
insert into productos (id, producto, precio) values (910, 'Pork - Smoked Kassler', 94);
insert into productos (id, producto, precio) values (911, 'Hand Towel', 31);
insert into productos (id, producto, precio) values (912, 'Pork - Loin, Center Cut', 97);
insert into productos (id, producto, precio) values (913, 'V8 - Tropical Blend', 10);
insert into productos (id, producto, precio) values (914, 'Sprouts - Baby Pea Tendrils', 17);
insert into productos (id, producto, precio) values (915, 'Bread - Sour Batard', 91);
insert into productos (id, producto, precio) values (916, 'Bread - Frozen Basket Variety', 39);
insert into productos (id, producto, precio) values (917, 'Soap - Hand Soap', 8);
insert into productos (id, producto, precio) values (918, 'Olives - Morracan Dired', 54);
insert into productos (id, producto, precio) values (919, 'Beer - Upper Canada Light', 99);
insert into productos (id, producto, precio) values (920, 'Onions - Pearl', 19);
insert into productos (id, producto, precio) values (921, 'Pork - Liver', 95);
insert into productos (id, producto, precio) values (922, 'Canada Dry', 14);
insert into productos (id, producto, precio) values (923, 'Pecan Raisin - Tarts', 53);
insert into productos (id, producto, precio) values (924, 'Bread - Crumbs, Bulk', 36);
insert into productos (id, producto, precio) values (925, 'Wine - Red, Marechal Foch', 75);
insert into productos (id, producto, precio) values (926, 'Wine - White, Pelee Island', 67);
insert into productos (id, producto, precio) values (927, 'Coffee - Decafenated', 93);
insert into productos (id, producto, precio) values (928, 'Cherries - Frozen', 10);
insert into productos (id, producto, precio) values (929, 'Doilies - 7, Paper', 8);
insert into productos (id, producto, precio) values (930, 'Mackerel Whole Fresh', 33);
insert into productos (id, producto, precio) values (931, 'Tea - Herbal Orange Spice', 43);
insert into productos (id, producto, precio) values (932, 'Tomato Paste', 88);
insert into productos (id, producto, precio) values (933, 'Muffin Mix - Chocolate Chip', 2);
insert into productos (id, producto, precio) values (934, 'Bread - Multigrain', 98);
insert into productos (id, producto, precio) values (935, 'Oil - Safflower', 34);
insert into productos (id, producto, precio) values (936, 'Soup - Campbells Pasta Fagioli', 57);
insert into productos (id, producto, precio) values (937, 'Wine - Chateau Bonnet', 60);
insert into productos (id, producto, precio) values (938, 'Pastry - Chocolate Marble Tea', 61);
insert into productos (id, producto, precio) values (939, 'Broom - Push', 29);
insert into productos (id, producto, precio) values (940, 'Ginger - Crystalized', 49);
insert into productos (id, producto, precio) values (941, 'Beer - Labatt Blue', 38);
insert into productos (id, producto, precio) values (942, 'Remy Red', 37);
insert into productos (id, producto, precio) values (943, 'Fish - Bones', 43);
insert into productos (id, producto, precio) values (944, 'Bread - Rolls, Rye', 32);
insert into productos (id, producto, precio) values (945, 'Tomato Puree', 31);
insert into productos (id, producto, precio) values (946, 'Soup - Campbells Asian Noodle', 2);
insert into productos (id, producto, precio) values (947, 'Ice Cream Bar - Oreo Cone', 23);
insert into productos (id, producto, precio) values (948, 'Croissants Thaw And Serve', 12);
insert into productos (id, producto, precio) values (949, 'Lobster - Baby, Boiled', 11);
insert into productos (id, producto, precio) values (950, 'Sage Derby', 56);
insert into productos (id, producto, precio) values (951, 'Pasta - Spaghetti, Dry', 38);
insert into productos (id, producto, precio) values (952, 'Sausage - Meat', 64);
insert into productos (id, producto, precio) values (953, 'Ecolab Digiclean Mild Fm', 73);
insert into productos (id, producto, precio) values (954, 'Lobster - Base', 27);
insert into productos (id, producto, precio) values (955, 'Piping Jelly - All Colours', 67);
insert into productos (id, producto, precio) values (956, 'Tomato - Tricolor Cherry', 18);
insert into productos (id, producto, precio) values (957, 'Oil - Olive', 29);
insert into productos (id, producto, precio) values (958, 'Toothpick Frilled', 48);
insert into productos (id, producto, precio) values (959, 'Beef - Tongue, Cooked', 71);
insert into productos (id, producto, precio) values (960, 'Trueblue - Blueberry Cranberry', 61);
insert into productos (id, producto, precio) values (961, 'Gherkin', 32);
insert into productos (id, producto, precio) values (962, 'Steampan - Half Size Shallow', 70);
insert into productos (id, producto, precio) values (963, 'Pork - Smoked Back Bacon', 45);
insert into productos (id, producto, precio) values (964, 'Clams - Littleneck, Whole', 18);
insert into productos (id, producto, precio) values (965, 'Cucumber - Pickling Ontario', 44);
insert into productos (id, producto, precio) values (966, 'Longos - Chicken Cordon Bleu', 46);
insert into productos (id, producto, precio) values (967, 'Garam Masala Powder', 71);
insert into productos (id, producto, precio) values (968, 'Canada Dry', 1);
insert into productos (id, producto, precio) values (969, 'Wine - Cave Springs Dry Riesling', 16);
insert into productos (id, producto, precio) values (970, 'Table Cloth 72x144 White', 86);
insert into productos (id, producto, precio) values (971, 'Swordfish Loin Portions', 80);
insert into productos (id, producto, precio) values (972, 'Calypso - Lemonade', 20);
insert into productos (id, producto, precio) values (973, 'Beef - Eye Of Round', 63);
insert into productos (id, producto, precio) values (974, 'Wine - Cave Springs Dry Riesling', 77);
insert into productos (id, producto, precio) values (975, 'Chocolate - Milk, Callets', 64);
insert into productos (id, producto, precio) values (976, 'Zucchini - Mini, Green', 49);
insert into productos (id, producto, precio) values (977, 'Pate - Cognac', 2);
insert into productos (id, producto, precio) values (978, 'Extract - Lemon', 7);
insert into productos (id, producto, precio) values (979, 'Liquid Aminios Acid - Braggs', 28);
insert into productos (id, producto, precio) values (980, 'Beef - Ox Tail, Frozen', 29);
insert into productos (id, producto, precio) values (981, 'Cake - Miini Cheesecake Cherry', 63);
insert into productos (id, producto, precio) values (982, 'Muffin Mix - Morning Glory', 74);
insert into productos (id, producto, precio) values (983, 'Garbage Bags - Clear', 79);
insert into productos (id, producto, precio) values (984, 'Island Oasis - Wildberry', 40);
insert into productos (id, producto, precio) values (985, 'Cheese - Le Cru Du Clocher', 74);
insert into productos (id, producto, precio) values (986, 'Munchies Honey Sweet Trail Mix', 49);
insert into productos (id, producto, precio) values (987, 'Pasta - Fett Alfredo, Single Serve', 81);
insert into productos (id, producto, precio) values (988, 'Cheese - Mix', 21);
insert into productos (id, producto, precio) values (989, 'Yogurt - French Vanilla', 99);
insert into productos (id, producto, precio) values (990, 'Pastry - Apple Large', 55);
insert into productos (id, producto, precio) values (991, 'Potatoes - Peeled', 10);
insert into productos (id, producto, precio) values (992, 'Curry Paste - Madras', 44);
insert into productos (id, producto, precio) values (993, 'Coconut - Whole', 13);
insert into productos (id, producto, precio) values (994, 'Apple - Granny Smith', 93);
insert into productos (id, producto, precio) values (995, 'Nantuket Peach Orange', 63);
insert into productos (id, producto, precio) values (996, 'Pastry - Choclate Baked', 25);
insert into productos (id, producto, precio) values (997, 'Skirt - 29 Foot', 58);
insert into productos (id, producto, precio) values (998, 'Bread - Italian Sesame Poly', 40);
insert into productos (id, producto, precio) values (999, 'Flour Pastry Super Fine', 17);
insert into productos (id, producto, precio) values (1000, 'Lettuce - Belgian Endive', 16);
