version: "3.6"

# Volumen compartido para simular HDFS
volumes:
  hdfs-simulado:
    name: "hadoop-distributed-file-system"
    driver: local

services:
  #Nodo maestro
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - hdfs-simulado:/opt/workspace
  # Worker 1
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    # Variables de entorno (pueden variarse según las necesidades)
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - hdfs-simulado:/opt/workspace
    depends_on:
      - spark-master
  # Worker 2
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - hdfs-simulado:/opt/workspace
    depends_on:
      - spark-master
  # Contenedor para el cuaderno 
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - hdfs-simulado:/opt/workspace
